
[env]
TERM = "tmux-256color"

[window]
decorations = "buttonless"

[window.padding]
x = 7
y = 7

[scrolling]
history = 10_000

[selection]
save_to_clipboard = true

[font]
size = 12

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Semibold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Light Italic"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "Q", mods = "Control", chars = "\u0011" },
  { key = "=", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },
]

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", action = "PasteSelection" }]

[general]
import = ["~/.config/alacritty/alacritty-theme/themes/dawnfox.toml"]
