# -*- mode: sh; -*-
#
# There are five startup files that zsh will read commands from:
#
# Documentation
# https://zsh.sourceforge.io/Intro/intro_3.html

# Locale
export LC_ALL=en_GB.UTF-8
export LC_CTYPE=en_GB.UTF-8
export LANG=en_GB.UTF-8

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH

# EDITOR
unset ALTERNATE_EDITOR
export EDITOR='nvim'
export PAGER='less -M'
export VISUAL=$EDITOR

# ZSH
export ZSH_THEME="sunrise"
export ZSH=$XDG_DATA_HOME"/oh-my-zsh"
export ZSH_CUSTOM=$ZDOTDIR/custom
export ZSH_CACHE_DIR=$XDG_CACHE_HOME/zsh
export HISTFILE=$ZSH_CACHE_DIR/zhistory

# SSH
export GIT_SSH_COMMAND="/usr/bin/ssh -F ${XDG_CONFIG_HOME}/ssh/config"

# GOLANG
export GOROOT="$(brew --prefix golang)/libexec"
export GOPATH=$HOME/go
export GOPRIVATE=gitlab.com/junitechnology/*
export GO111MODULE=on

# AWS no pager
export AWS_PAGER=""

# BREW
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1

# PATH
## Home Path
export PATH="$PATH:$HOME/.config/dotfiles/scripts"
export PATH="$PATH:$HOME/.local/bin"

# Go
export PATH=$PATH:$GOPATH/bin

export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/config.toml"

# Completions
fpath+=($ZDOTDIR/completions)
