# -*- mode: sh; -*-

# Locale
export LC_ALL=en_GB.UTF-8
export LC_CTYPE=en_GB.UTF-8
export LANG=en_GB.UTF-8

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH

## PATH
# Home Path
export PATH="$PATH:$HOME/.config/dotfiles/scripts"
export PATH="$PATH:$HOME/.local/bin"
# Python
export PATH="$PATH:/Users/larsbackman/Library/Python/3.9/bin"

# EDITOR
unset ALTERNATE_EDITOR
export EDITOR='nvim'
export PAGER='less -M'
export VISUAL=$EDITOR

# ZSH
export ZSH_THEME="sunrise"
export ZSH=$XDG_DATA_HOME"/oh-my-zsh"
export ZSH_CUSTOM=$ZDOTDIR/custom
export ZSH_CACHE_DIR=$XDG_CACHE_HOME/zsh
export HISTFILE=$ZSH_CACHE_DIR/zhistory
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Bat
export BAT_THEME="base16"

# SSH
export GIT_SSH_COMMAND="/usr/bin/ssh -F ${XDG_CONFIG_HOME}/ssh/config"

# Completions
fpath+=($ZDOTDIR/completions)

# GOLANG
export GOROOT="$(brew --prefix golang)/libexec"
export GOPATH=$HOME/go
export GOPRIVATE=gitlab.com/junitechnology/*
export GO111MODULE=on
export PATH=$PATH:$GOPATH/bin
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"

# AWS no pager
export AWS_PAGER=""

# mode
export MODE=$(grep -i 'zenkan_\(light\|dark\)' ${HOME}/.config/alacritty/alacritty.toml | awk -F'[_,\.]' '{print $3}')

# BREW
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1

source ${ZDOTDIR}/.zshenv_local
