# Create ZSH cache directory unless it already exists
[[ -d $ZSH_CACHE_DIR ]] || mkdir -p $ZSH_CACHE_DIR

# Vi mode
bindkey -v
export KEYTIMEOUT=5
# change cursor shape in vi mode
zle-keymap-select () {
    if [[ $KEYMAP == vicmd ]]; then
        # the command mode for vi
        echo -ne "\e[2 q"
    else
        # the insert mode for vi
        echo -ne "\e[5 q"
    fi
}
zle -N zle-keymap-select

# Reverse search
bindkey '^R' history-incremental-search-backward

# Start tmux
if [[ $TMUX = "" ]] then
  main_session_name="main"
  if ! tmux has-session -t main 2>/dev/null; then 
    tmux new -s $main_session_name
  else
    tmux attach-session -t $main_session_name
  fi
fi

# Aliases
alias vim='nvim'
alias vi='nvim'
alias vimdiff='nvim -d'
alias vis='EDITOR=vim visudo -f'
# Remap old commands
alias l='eza -l'
alias la='eza -al'
alias ls='eza'
alias tree='eza -T'
alias t='eza -T'
alias cat='bat'

# SSH
if [ -s "${XDG_CONFIG_HOME}/ssh/config" ]
then
  SSH_CONFIG="-F ${XDG_CONFIG_HOME}/ssh/config"
fi
if [ -s "${XDG_CONFIG_HOME}/ssh/id_ed25519" ]
then
  SSH_ID="-i ${XDG_CONFIG_HOME}/ssh/id_ed25519"
fi
alias ssh="ssh $SSH_CONFIG $SSH_ID "

# AWS
function aws_environment {
  if [ -z $1 ]
  then
    env=$(awk '/\[profile|sso_role_name/{print $NF}' ${HOME}/.aws/config | sed 's/\]//g' | paste -d " " - - | sort | fzf | cut -d' ' -f1)
  else
    env=$1
  fi
    eval `/bin/bash ${XDG_CONFIG_HOME}/tmux/scripts/aws-sso-assume-role.sh $env`
}

FPATH="/opt/homebrew/share/zsh/site-functions:${FPATH}"

# zsh plugins
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#c4b8c0"
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Tab accepts one word of autosuggestion at a time, otherwise normal completion
_autosuggest_or_complete() {
  if [[ -n $POSTDISPLAY ]]; then
    zle forward-word
  else
    zle expand-or-complete
  fi
}
zle -N _autosuggest_or_complete
bindkey '\t' _autosuggest_or_complete

# pyenv (lazy-loaded)
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
pyenv() {
  unfunction pyenv
  eval "$(command pyenv init - zsh)"
  pyenv "$@"
}

autoload bashcompinit && bashcompinit
autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ${ZDOTDIR:-~}/.zcompdump 2>/dev/null) ]; then
  compinit
else
  compinit -C
fi
complete -C '/usr/local/bin/aws_completer' aws
complete -o nospace -C /opt/homebrew/bin/terraform terraform
eval "$(zoxide init zsh)"
alias j='z'
eval "$(direnv hook zsh)"
eval "$(atuin init zsh --disable-up-arrow)"

source "${ZDOTDIR}/.zshrc_local"
eval "$(starship init zsh)"
export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"

. "$HOME/.local/share/../bin/env"
source ~/.safe-chain/scripts/init-posix.sh # Safe-chain Zsh initialization script

# zsh-syntax-highlighting must be sourced last
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
